"""TEE EQUAL BV CS SCH40 ASTM A234-WPB ASME B16.9

NATIVE reconstruction of Plant 3D CPTS. Dimensions from CATA_NUI.xlsx
sheet "TEE EQUAL_SCH40_BW". Auto-generated by scripts/gen_native_parts.py — do not edit by hand.
"""

import native_shapes
import pipe_sizes

# DN -> (D1, D3, L1, L2, L3, A, wall)
DIMENSIONS = {
    15: (21.34, 0.0, 25.0, 0.0, 0.0, 90.0, 3.73),
    20: (26.67, 0.0, 29.0, 0.0, 0.0, 90.0, 3.91),
    25: (33.4, 0.0, 38.0, 0.0, 0.0, 90.0, 4.55),
    32: (42.16, 0.0, 48.0, 0.0, 0.0, 90.0, 4.85),
    40: (48.26, 0.0, 57.0, 0.0, 0.0, 90.0, 5.08),
    50: (60.32, 0.0, 64.0, 0.0, 0.0, 90.0, 3.91),
    65: (73.03, 0.0, 76.0, 0.0, 0.0, 90.0, 4.78),
    80: (88.9, 0.0, 86.0, 0.0, 0.0, 90.0, 5.49),
    90: (90.0, 0.0, 95.0, 0.0, 0.0, 90.0, 5.74),
    100: (114.3, 0.0, 105.0, 0.0, 0.0, 90.0, 6.02),
    125: (125.0, 0.0, 124.0, 0.0, 0.0, 90.0, 6.55),
    150: (168.3, 0.0, 143.0, 0.0, 0.0, 90.0, 7.11),
    200: (219.1, 0.0, 178.0, 0.0, 0.0, 90.0, 8.18),
    250: (273.1, 0.0, 216.0, 0.0, 0.0, 90.0, 9.27),
    300: (323.9, 0.0, 254.0, 0.0, 0.0, 90.0, 10.31),
    350: (355.6, 0.0, 279.0, 0.0, 0.0, 90.0, 11.13),
    400: (406.4, 0.0, 305.0, 0.0, 0.0, 90.0, 12.7),
    450: (457.2, 0.0, 343.0, 0.0, 0.0, 90.0, 14.27),
}


class TEE_EQUAL_SCH40_BW(native_shapes.NativeTee):
    def __init__(self, s, size, *, add_ports=True):
        key = pipe_sizes.resolve_dn(size)
        if key not in DIMENSIONS:
            raise ValueError(f"No TEE_EQUAL_SCH40_BW data for {key}.")
        D1, D3, L1, L2, L3, A, wall = DIMENSIONS[key]
        super().__init__(s, D1, D3, L1, L2, L3, A, wall, add_ports=add_ports)
