"""FLANGE SO FL RF CL150 CS ASTM A105N ASME B16.5

NATIVE reconstruction of Plant 3D CPFWR_F_SF. Dimensions from CATA_NUI.xlsx
sheet "FLANGE SO_CL150_RF". Auto-generated by scripts/gen_native_parts.py — do not edit by hand.
"""

import native_shapes
import pipe_sizes

# DN -> (L, B, D1, D2, D3, I)
DIMENSIONS = {
    15: (15.5, 11.2, 89.0, 22.2, 30.0, 14.0),
    20: (15.5, 12.7, 99.0, 27.7, 38.0, 14.0),
    25: (17.5, 14.2, 108.0, 34.5, 49.0, 16.0),
    32: (20.5, 15.7, 117.0, 43.2, 59.0, 19.0),
    40: (22.5, 17.4, 127.0, 49.5, 65.0, 21.0),
    50: (25.5, 19.0, 152.0, 61.9, 78.0, 24.0),
    65: (28.5, 22.1, 178.0, 74.6, 90.0, 27.0),
    80: (30.5, 23.9, 190.0, 90.7, 108.0, 29.0),
    90: (31.5, 23.9, 216.0, 103.4, 122.0, 30.0),
    100: (33.5, 23.9, 229.0, 116.8, 135.0, 32.0),
    125: (36.5, 23.9, 254.0, 143.8, 164.0, 35.0),
    150: (39.5, 25.4, 279.0, 170.7, 192.0, 38.0),
    200: (44.5, 28.4, 343.0, 221.5, 246.0, 43.0),
    250: (49.5, 29.9, 406.0, 276.2, 305.0, 48.0),
    300: (55.5, 31.7, 483.0, 327.0, 365.0, 54.0),
    350: (57.5, 34.8, 533.0, 359.2, 400.0, 56.0),
    400: (63.5, 36.6, 597.0, 410.5, 457.0, 62.0),
    450: (68.5, 39.6, 635.0, 461.8, 505.0, 67.0),
}


class FLANGE_SO_CL150_RF(native_shapes.NativeSlipOnFlange):
    def __init__(self, s, size, *, add_ports=True):
        key = pipe_sizes.resolve_dn(size)
        if key not in DIMENSIONS:
            raise ValueError(f"No FLANGE_SO_CL150_RF data for {key}.")
        L, B, D1, D2, D3, I = DIMENSIONS[key]
        super().__init__(s, L, B, D1, D2, D3, socket_depth=I, add_ports=add_ports)
