"""STUB END_LONG_SCH40_BW

NATIVE reconstruction of Plant 3D CPMUW. Dimensions from CATA_NUI.xlsx
sheet "STUB END_LONG_SCH40_BW". Auto-generated by scripts/gen_native_parts.py — do not edit by hand.
"""

import native_shapes
import pipe_sizes

# DN -> (L, B, D1, D2, wall)
DIMENSIONS = {
    15: (76.0, 2.77, 35.0, 21.34, 2.77),
    20: (76.0, 2.87, 49.0, 26.67, 2.87),
    25: (102.0, 3.38, 51.0, 33.4, 3.38),
    32: (102.0, 3.56, 64.0, 42.16, 3.56),
    40: (102.0, 3.68, 73.0, 48.26, 3.68),
    50: (152.0, 3.91, 92.0, 60.32, 3.91),
    65: (152.0, 5.16, 105.0, 73.03, 5.16),
    80: (152.0, 5.49, 127.0, 88.9, 5.49),
    90: (152.0, 5.74, 140.0, 90.0, 5.74),
    100: (152.0, 6.02, 157.0, 114.3, 6.02),
    125: (203.0, 6.55, 186.0, 125.0, 6.55),
    150: (203.0, 7.11, 216.0, 168.3, 7.11),
    200: (203.0, 8.18, 270.0, 219.1, 8.18),
    250: (254.0, 9.27, 324.0, 273.1, 9.27),
    300: (254.0, 9.53, 381.0, 323.9, 9.53),
    350: (305.0, 9.53, 413.0, 355.6, 9.53),
    400: (305.0, 9.53, 470.0, 406.4, 9.53),
    450: (305.0, 9.53, 533.0, 457.2, 9.53),
}


class STUB_END_LONG_SCH40_BW(native_shapes.NativeStubEnd):
    def __init__(self, s, size, *, add_ports=True):
        key = pipe_sizes.resolve_dn(size)
        if key not in DIMENSIONS:
            raise ValueError(f"No STUB_END_LONG_SCH40_BW data for {key}.")
        L, B, D1, D2, wall = DIMENSIONS[key]
        super().__init__(s, L, B, D1, D2, wall, add_ports=add_ports)
