// <auto-generated by scripts/sync_lap_joint_cs_tables.py — do not edit by hand>

using System;
using System.Collections.Generic;
using System.Linq;

namespace Plant3DCatalogComposer.Services
{
    /// <summary>CL150 lap-joint backing ring — Plant L,D2 + Iplex OD/tf (mm).</summary>
    internal static class CatalogLjRingCl150Table
    {
        internal sealed record LjRingDims(double L, double D1, double D2, double Tf);

        private static readonly Dictionary<int, (double L, double D1, double D2, double Tf)> ByDn = new()
        {
            [15] = (15.75, 89, 22.86, 11.2),
            [20] = (15.75, 99, 28.19, 12.7),
            [25] = (17.53, 108, 35.05, 14.2),
            [32] = (20.57, 117, 43.69, 15.7),
            [40] = (22.35, 127, 50.04, 17.5),
            [50] = (25.4, 152, 62.48, 19),
            [65] = (28.45, 178, 74.68, 22.4),
            [80] = (30.23, 191, 91.44, 23.9),
            [90] = (31.75, 216, 104.14, 23.9),
            [100] = (33.27, 229, 116.84, 23.9),
            [125] = (36.58, 254, 144.53, 23.9),
            [150] = (39.62, 279, 171.45, 25.4),
            [200] = (44.45, 343, 222.25, 28.4),
            [250] = (49.28, 406, 277.37, 30.2),
            [300] = (55.63, 483, 328.17, 31.8),
            [350] = (79.25, 533, 360.17, 35.1),
            [400] = (87.38, 597, 411.23, 36.6),
            [450] = (96.77, 635, 462.28, 39.6),
        };

        public static IReadOnlyList<int> AllDns { get; } = ByDn.Keys.OrderBy(k => k).ToList();

        public static bool TryGet(int dn, out LjRingDims dims)
        {
            if (!ByDn.TryGetValue(dn, out (double L, double D1, double D2, double Tf) row))
            {
                dims = default!;
                return false;
            }
            dims = new LjRingDims(row.L, row.D1, row.D2, row.Tf);
            return true;
        }

        public static LjRingDims Get(int dn) =>
            TryGet(dn, out LjRingDims dims)
                ? dims
                : throw new InvalidOperationException($"No CL150 LJ ring for DN {dn}.");
    }
}
