// <auto-generated by scripts/sync_lap_joint_cs_tables.py — do not edit by hand>

using System;
using System.Collections.Generic;
using System.Linq;

namespace Plant3DCatalogComposer.Services
{
    /// <summary>CL150 lap-joint flat plate — ASME B16.5 Table 7 O/W + Table 8 tf (mm).</summary>
    internal static class CatalogLjRingCl150Table
    {
        internal sealed record LjRingDims(double L, double D1, double D2, double Tf);

        private static readonly Dictionary<int, (double L, double D1, double D2, double Tf)> ByDn = new()
        {
            [15] = (11.2, 90, 21.3, 11.2),
            [20] = (12.7, 100, 26.7, 12.7),
            [25] = (14.3, 110, 33.4, 14.3),
            [32] = (15.9, 115, 42.2, 15.9),
            [40] = (17.5, 125, 48.3, 17.5),
            [50] = (19.1, 150, 60.3, 19.1),
            [65] = (22.3, 180, 73, 22.3),
            [80] = (23.9, 190, 88.9, 23.9),
            [90] = (23.9, 215, 101.6, 23.9),
            [100] = (23.9, 230, 114.3, 23.9),
            [125] = (23.9, 255, 141.3, 23.9),
            [150] = (25.4, 280, 168.3, 25.4),
            [200] = (28.6, 345, 219.1, 28.6),
            [250] = (30.2, 405, 273, 30.2),
            [300] = (31.8, 485, 323.8, 31.8),
            [350] = (35, 535, 355.6, 35),
            [400] = (36.6, 595, 406.4, 36.6),
            [450] = (39.7, 635, 457.2, 39.7),
        };

        public static IReadOnlyList<int> AllDns { get; } = ByDn.Keys.OrderBy(k => k).ToList();

        public static bool TryGet(int dn, out LjRingDims dims)
        {
            if (!ByDn.TryGetValue(dn, out (double L, double D1, double D2, double Tf) row))
            {
                dims = default!;
                return false;
            }
            dims = new LjRingDims(row.L, row.D1, row.D2, row.Tf);
            return true;
        }

        public static LjRingDims Get(int dn) =>
            TryGet(dn, out LjRingDims dims)
                ? dims
                : throw new InvalidOperationException($"No CL150 LJ ring for DN {dn}.");
    }
}
