// <auto-generated by scripts/sync_lap_joint_cs_tables.py — do not edit by hand>

using System;
using System.Collections.Generic;
using System.Linq;

namespace Plant3DCatalogComposer.Services
{
    /// <summary>ASME B16.9 Type A lap-joint stub end — STUBEND TABLE (mm).</summary>
    internal static class CatalogStubEndTable
    {
        internal enum Pattern { Long, Short }

        /// <summary>L=total length, B=lap thickness, D1=lap OD, D2=do at weld.</summary>
        internal sealed record StubEndDims(double L, double B, double D1, double D2);

        private static readonly Dictionary<int, (double Do, double FSh, double FLg, double G, double StubThk)> ByDn = new()
        {
            [15] = (21, 51, 76, 35, 2.77),
            [20] = (27, 51, 76, 42.9, 2.87),
            [25] = (33, 51, 102, 51, 3.38),
            [32] = (42, 51, 102, 64, 3.56),
            [40] = (48, 51, 102, 73, 3.68),
            [50] = (60, 64, 152, 92, 3.91),
            [65] = (73, 64, 152, 105, 5.16),
            [80] = (89, 64, 152, 127, 5.49),
            [90] = (102, 76, 152, 140, 5.74),
            [100] = (114, 76, 152, 157, 6.02),
            [125] = (141, 76, 203, 186, 6.55),
            [150] = (168, 89, 203, 216, 7.11),
            [200] = (219, 102, 203, 270, 8.18),
            [250] = (273, 127, 254, 324, 9.27),
            [300] = (324, 152, 254, 381, 9.53),
            [350] = (356, 152, 305, 413, 9.53),
            [400] = (406, 152, 305, 470, 9.53),
            [450] = (457, 152, 305, 533, 9.53),
            [500] = (508, 152, 305, 584, 9.53),
            [550] = (559, 152, 305, 641, 9.53),
            [600] = (610, 152, 305, 692, 9.53),
        };

        public static IReadOnlyList<int> AllDns { get; } = ByDn.Keys.OrderBy(k => k).ToList();

        public static Pattern ResolvePattern(string partId)
        {
            if (partId.StartsWith("COLLAR_LJ_", StringComparison.OrdinalIgnoreCase))
                partId = CatalogLapJointIds.StubExportIdFromCollar(partId);

            return partId.Contains("_SH_", StringComparison.OrdinalIgnoreCase)
                ? Pattern.Short
                : Pattern.Long;
        }

        public static bool TryGet(int dn, Pattern pattern, out StubEndDims dims)
        {
            if (!ByDn.TryGetValue(dn, out (double Do, double FSh, double FLg, double G, double StubThk) row))
            {
                dims = default!;
                return false;
            }

            double l = pattern == Pattern.Short ? row.FSh : row.FLg;
            dims = new StubEndDims(l, row.StubThk, row.G, row.Do);
            return true;
        }

        public static bool TryGet(int dn, out StubEndDims dims) => TryGet(dn, Pattern.Long, out dims);

        /// <summary>Lap thickness B (mm) — same for long/short pattern.</summary>
        public static bool TryGetLapThickness(int dn, out double lapMm)
        {
            if (!ByDn.TryGetValue(dn, out (double Do, double FSh, double FLg, double G, double StubThk) row))
            {
                lapMm = 0;
                return false;
            }
            lapMm = row.StubThk;
            return true;
        }

        /// <summary>Stub OD at pipe weld (do / catalog D2) — MatchingPipeOd for all lap-joint ports.</summary>
        public static bool TryGetWeldDo(int dn, out double doMm)
        {
            if (!ByDn.TryGetValue(dn, out (double Do, double FSh, double FLg, double G, double StubThk) row))
            {
                doMm = 0;
                return false;
            }
            doMm = row.Do;
            return true;
        }

        public static StubEndDims Get(int dn, Pattern pattern) =>
            TryGet(dn, pattern, out StubEndDims dims)
                ? dims
                : throw new InvalidOperationException($"No stub end table row for DN {dn}.");
    }
}
