using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Plant3DSkeletonManager.Core;

namespace Plant3DCatalogComposer.Services
{
    /// <summary>Generates composer_live.py for the Python tab (readable primitives.py-style script).</summary>
    internal static class PythonCodeGenerator
    {
        public static string Generate(ValveProject project, bool forCatalogPackage = false)
        {
            var sb = new StringBuilder();
            AppendBuildHeader(sb, project);
            sb.AppendLine("def build(s):");
            sb.AppendLine($"    \"\"\"Scene: {EscapePy(project.ValveName)} — {project.Parts.Count} part(s).\"\"\"");
            AppendBuildBody(sb, project, "    ", returnResult: true, forCatalogPackage);
            return sb.ToString();
        }

        /// <summary>Geometry lines for catalog class; assigns final shape to <c>geom</c>.</summary>
        public static string GenerateBuildBody(ValveProject project, bool forCatalogPackage = false)
        {
            if (project.Parts.Count == 0)
                return "        geom = None";

            var sb = new StringBuilder();
            AppendBuildBody(sb, project, "        ", returnResult: false, forCatalogPackage);
            return sb.ToString().TrimEnd();
        }

        private static void AppendBuildHeader(StringBuilder sb, ValveProject project)
        {
            var catalogImports = project.Parts
                .Where(p => p.Kind == SceneNodeKind.Catalog && !string.IsNullOrEmpty(p.CatalogPartId))
                .Select(p => $"CUST_{p.CatalogPartId}")
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderBy(x => x)
                .ToList();

            sb.AppendLine("\"\"\"Auto-generated by Plant 3D Catalog Composer — edits overwritten on Apply/Insert/Move.\"\"\"");
            sb.AppendLine();
            sb.AppendLine("from primitives import (");
            sb.AppendLine("    Box, Cone, Cylinder, Elbow, EllipsoidHead, EllipsoidHead2,");
            sb.AppendLine("    EllipsoidSegment, HalfSphere, Pyramid, Reduced_elbow,");
            sb.AppendLine("    RoundRectangle, SegmentedElbow, ShapeAssembly, Sphere,");
            sb.AppendLine("    SphereSegment, TorisPhericHead, TorisPhericHead2, TorisPhericHeadH, Torus,");
            sb.AppendLine(")");
            foreach (string fn in catalogImports)
                sb.AppendLine($"from {fn} import {fn}");
            sb.AppendLine();
            sb.AppendLine();
        }

        private static void AppendBuildBody(
            StringBuilder sb,
            ValveProject project,
            string indent,
            bool returnResult,
            bool forCatalogPackage = false)
        {
            if (project.Parts.Count == 0)
            {
                sb.AppendLine(returnResult ? $"{indent}return None" : $"{indent}geom = None");
                return;
            }

            var varNames = new Dictionary<Guid, string>();
            foreach (PrimitiveNode part in project.Parts)
            {
                string vn = VarName(part);
                varNames[part.Id] = vn;
                if (part.Kind == SceneNodeKind.Catalog && !string.IsNullOrEmpty(part.CatalogPartId))
                {
                    string fn = $"CUST_{part.CatalogPartId}";
                    sb.AppendLine($"{indent}{vn} = {BuildCatalogCall(part, fn, forCatalogPackage)}");
                }
                else
                {
                    sb.AppendLine($"{indent}{vn} = {BuildPrimitiveCall(part, forCatalogPackage, project.Parameters)}");
                }

                AppendTransformChain(sb, vn, part, indent);
            }

            var activeIds = new HashSet<Guid>(project.Parts.Select(p => p.Id));

            foreach (BooleanOperation op in project.Operations.OrderBy(o => o.Order))
            {
                if (!varNames.TryGetValue(op.Target, out string? targetVar))
                    continue;

                var toolVars = new List<string>();
                foreach (Guid tid in op.Tools)
                {
                    if (varNames.TryGetValue(tid, out string? tv))
                        toolVars.Add(tv);
                }

                if (toolVars.Count == 0 && op.Type != BooleanOpType.INTERSECT)
                    continue;

                switch (op.Type)
                {
                    case BooleanOpType.UNION:
                        sb.AppendLine($"{indent}{targetVar} = {targetVar}.combine([{string.Join(", ", toolVars)}])");
                        foreach (Guid tid in op.Tools)
                            activeIds.Remove(tid);
                        break;
                    case BooleanOpType.SUBTRACT:
                        sb.AppendLine($"{indent}{targetVar} = {targetVar}.subtract([{string.Join(", ", toolVars)}])");
                        foreach (Guid tid in op.Tools)
                            activeIds.Remove(tid);
                        break;
                    case BooleanOpType.INTERSECT when toolVars.Count == 1:
                        sb.AppendLine($"{indent}{targetVar} = {targetVar}.intersect({toolVars[0]})");
                        activeIds.Remove(op.Tools[0]);
                        break;
                }
            }

            var liveVars = activeIds
                .Where(id => varNames.ContainsKey(id))
                .Select(id => varNames[id])
                .ToList();

            if (liveVars.Count == 0)
            {
                sb.AppendLine(returnResult ? $"{indent}return None" : $"{indent}geom = None");
                return;
            }

            if (liveVars.Count == 1)
            {
                sb.AppendLine(returnResult
                    ? $"{indent}return {liveVars[0]}.set_color(120)"
                    : $"{indent}geom = {liveVars[0]}");
                return;
            }

            string root = liveVars[0];
            for (int i = 1; i < liveVars.Count; i++)
                sb.AppendLine($"{indent}{root} = {root}.combine([{liveVars[i]}])");

            sb.AppendLine(returnResult
                ? $"{indent}return {root}.set_color(120)"
                : $"{indent}geom = {root}");
        }

        private static string BuildCatalogCall(PrimitiveNode node, string fn, bool forCatalogPackage)
        {
            if (forCatalogPackage &&
                !string.IsNullOrEmpty(node.CatalogPartId) &&
                CatalogPortTemplates.TryResolveLibraryClassName(node.CatalogPartId) is string className)
            {
                return BuildCatalogClassCall(node, className);
            }

            var args = new List<string> { "s" };
            foreach (KeyValuePair<string, ParamValue> kv in node.Parameters.OrderBy(k => k.Key))
            {
                if (kv.Key.Equals("DN", StringComparison.OrdinalIgnoreCase))
                    args.Add($"DN={FmtInt(kv.Value.Value)}");
                else if (kv.Key.Equals("CEL", StringComparison.OrdinalIgnoreCase))
                {
                    if (Math.Abs(kv.Value.Value) > 1e-9)
                        args.Add($"CEL={Fmt(kv.Value.Value)}");
                }
                else
                    args.Add($"{kv.Key}={Fmt(kv.Value.Value)}");
            }

            if (forCatalogPackage)
                args.Add("preview=True");

            return $"{fn}({string.Join(", ", args)})";
        }

        /// <summary>Nested catalog part inside exported CUST_*.py — call geometry class, not @activate entry.</summary>
        private static string BuildCatalogClassCall(PrimitiveNode node, string className)
        {
            var args = new List<string> { "s" };

            double dn = 100;
            if (node.Parameters.TryGetValue("DN", out ParamValue? dnPv))
                dn = dnPv.Value;

            args.Add(FmtInt(dn));

            if (node.Parameters.TryGetValue("CEL", out ParamValue? celPv) && Math.Abs(celPv.Value) > 1e-9)
                args.Add($"cel_mm={Fmt(celPv.Value)}");

            args.Add("add_ports=False");
            return $"{className}({string.Join(", ", args)})";
        }

        private static string BuildPrimitiveCall(
            PrimitiveNode node,
            bool forCatalogPackage = false,
            SkeletonParameters? catalogSkeleton = null)
        {
            double N(string k, double d = 0) => Param(node, k, d);
            string Dim(string k, double d = 0) =>
                forCatalogPackage && catalogSkeleton != null
                    ? SceneParamBindingService.FormatCatalogDimensionRef(
                        node.Parameters.TryGetValue(k, out ParamValue? pv) ? pv : null,
                        catalogSkeleton,
                        N(k, d))
                    : Fmt(N(k, d));
            string BendRadius() =>
                forCatalogPackage
                    ? "BendRadius"
                    : Fmt(FittingDimensionService.ResolveElbowBendRadiusMm(
                        node,
                        new SkeletonParameters { BodyOD = N("D", 0) }));

            return node.Type switch
            {
                PrimitiveType.BOX =>
                    $"Box(s, length={Dim("L")}, width={Dim("W")}, height={Dim("H")})",
                PrimitiveType.CYLINDER => BuildCylinder(node, forCatalogPackage, catalogSkeleton),
                PrimitiveType.CONE =>
                    $"Cone(s, bottom_diameter={Dim("D1")}, height={Dim("H")}, top_diameter={Dim("D2")}, eccentricity={Dim("E")})",
                PrimitiveType.TORUS =>
                    $"Torus(s, diameter={Dim("D")}, thickness={Dim("T")})",
                PrimitiveType.SPHERE =>
                    $"Sphere(s, radius={Dim("R")})",
                PrimitiveType.HALFSPHERE =>
                    $"HalfSphere(s, radius={Dim("R")})",
                PrimitiveType.REDUCED_ELBOW =>
                    $"Reduced_elbow(s, diameter1={Dim("D")}, diameter2={Dim("D2")}, bend_radius={BendRadius()}, angle={Dim("A", 90)})",
                PrimitiveType.ELBOW =>
                    $"Elbow(s, diameter={Dim("D")}, bend_radius={BendRadius()}, angle={Dim("A", 90)})",
                PrimitiveType.SEGMENTED_ELBOW =>
                    $"SegmentedElbow(s, diameter={Dim("D")}, bend_radius={BendRadius()}, angle={Dim("A", 90)}, segments={FmtInt(N("S", 4))})",
                PrimitiveType.ELLIPSOID_HEAD =>
                    $"EllipsoidHead(s, diameter={Fmt(N("D"))})",
                PrimitiveType.ELLIPSOID_HEAD2 =>
                    $"EllipsoidHead2(s, diameter={Fmt(N("D"))})",
                PrimitiveType.ELLIPSOID_SEGMENT =>
                    $"EllipsoidSegment(s, radius_X={Fmt(N("RX"))}, radius_Y={Fmt(N("RY"))}, angle={Fmt(N("A1"))}, rotation_start={Fmt(N("A2"))}, angle_start={Fmt(N("A3"))}, angle_end={Fmt(N("A4", 360))})",
                PrimitiveType.PYRAMID =>
                    $"Pyramid(s, base_length={Fmt(N("L"))}, base_width={Fmt(N("W"))}, frustum_height={Fmt(N("H"))}, total_height={Fmt(N("HT"))})",
                PrimitiveType.ROUND_RECTANGLE =>
                    $"RoundRectangle(s, base_length={Fmt(N("L"))}, base_width={Fmt(N("W"))}, height={Fmt(N("H"))}, diam={Fmt(N("R2") * 2)}, eccentricity={Fmt(N("E"))})",
                PrimitiveType.SPHERE_SEGMENT =>
                    $"SphereSegment(s, radius={Fmt(N("R"))}, segment_height={Fmt(N("H"))}, start_height={Fmt(N("SH"))})",
                PrimitiveType.TORISPHERIC_HEAD =>
                    $"TorisPhericHead(s, diameter={Fmt(N("D"))})",
                PrimitiveType.TORISPHERIC_HEAD2 =>
                    $"TorisPhericHead2(s, diameter={Fmt(N("D"))})",
                PrimitiveType.TORISPHERIC_HEAD_H =>
                    $"TorisPhericHeadH(s, diameter={Fmt(N("D"))}, height={Fmt(N("H"))})",
                PrimitiveType.FILLET =>
                    $"Fillet(s, radius={Fmt(N("R"))}, height={Fmt(N("H"))}, angle={Fmt(N("A", 90))})",
                PrimitiveType.CYLINDER_CHAMFERED =>
                    $"CylinderChamfered(s, diameter={Fmt(N("D"))}, height={Fmt(N("L"))}, chamfer={Fmt(N("C"))}, chamfer_angle={Fmt(N("CA", 45))}, double_chamfer={BoolLit(N("DF"))})",
                PrimitiveType.BOX_WITH_FILLET =>
                    $"BoxWithFillet(s, length={Fmt(N("L"))}, width={Fmt(N("W"))}, height={Fmt(N("H"))}, radius={Fmt(N("R"))}, number_of_fillets={FmtInt(N("NF", 4))})",
                PrimitiveType.CYLINDER_WITH_FILLET =>
                    $"CylinderWithFillet(s, diameter={Fmt(N("D"))}, height={Fmt(N("L"))}, fillet_radius={Fmt(N("FR"))}, double_fillet={BoolLit(N("DF"))})",
                _ => $"Box(s, length=50, width=50, height=50)  # unsupported type {node.Type}",
            };
        }

        private static string BoolLit(double v) => v >= 0.5 ? "True" : "False";

        private static string BuildCylinder(
            PrimitiveNode node,
            bool forCatalogPackage = false,
            SkeletonParameters? catalogSkeleton = null)
        {
            double N(string k, double d = 0) => Param(node, k, d);
            string Dim(string k, double d = 0) =>
                forCatalogPackage && catalogSkeleton != null
                    ? SceneParamBindingService.FormatCatalogDimensionRef(
                        node.Parameters.TryGetValue(k, out ParamValue? pv) ? pv : null,
                        catalogSkeleton,
                        N(k, d))
                    : Fmt(N(k, d));

            double d = N("D");
            double h = N("L");
            double o = N("O", d / 2);
            double wall = Math.Max(0, d / 2 - o);
            double r2 = N("R2");
            bool ellipse = r2 > 1e-9 && Math.Abs(r2 - d / 2) > 1e-9;

            if (ellipse)
            {
                return $"Cylinder(s, diameter={Dim("D")}, height={Dim("L")}, wall_thickness={Fmt(wall)}, ellipse_diameter={Fmt(r2)})";
            }

            if (wall > 1e-9)
                return $"Cylinder(s, diameter={Dim("D")}, height={Dim("L")}, wall_thickness={Fmt(wall)})";

            return $"Cylinder(s, diameter={Dim("D")}, height={Dim("L")})";
        }

        private static void AppendTransformChain(StringBuilder sb, string varName, PrimitiveNode node, string indent = "    ")
        {
            if (node.RotationJogs is { Count: > 0 })
            {
                AppendJogReplayChain(sb, varName, node, indent);
                return;
            }

            double x = node.Origin.Length > 0 ? node.Origin[0] : 0;
            double y = node.Origin.Length > 1 ? node.Origin[1] : 0;
            double z = node.Origin.Length > 2 ? node.Origin[2] : 0;
            bool hasMove = Math.Abs(x) > 1e-9 || Math.Abs(y) > 1e-9 || Math.Abs(z) > 1e-9;
            bool hasRot = TryEulerDegrees(node.Rotation, out double rx, out double ry, out double rz);

            if (hasMove)
                sb.AppendLine($"{indent}{varName} = {varName}.move(x={Fmt(x)}, y={Fmt(y)}, z={Fmt(z)})");

            if (hasRot)
            {
                if (Math.Abs(rz) > 1e-6)
                    sb.AppendLine($"{indent}{varName} = {varName}.rotateZ({Fmt(rz)})");
                if (Math.Abs(ry) > 1e-6)
                    sb.AppendLine($"{indent}{varName} = {varName}.rotateY({Fmt(ry)})");
                if (Math.Abs(rx) > 1e-6)
                    sb.AppendLine($"{indent}{varName} = {varName}.rotateX({Fmt(rx)})");
            }
        }

        private static void AppendJogReplayChain(StringBuilder sb, string varName, PrimitiveNode node, string indent)
        {
            double x = node.Origin.Length > 0 ? node.Origin[0] : 0;
            double y = node.Origin.Length > 1 ? node.Origin[1] : 0;
            double z = node.Origin.Length > 2 ? node.Origin[2] : 0;
            bool hasMove = Math.Abs(x) > 1e-9 || Math.Abs(y) > 1e-9 || Math.Abs(z) > 1e-9;
            double[]? catFrame = node.CatalogFrameRotation is { Length: 9 } cf ? cf : null;
            bool hasCatFrame = catFrame != null && !TransformMath.IsIdentityRotation(catFrame);
            TransformMath.MapWorldVectorToBuildFrame(catFrame, x, y, z, out double mx, out double my, out double mz);
            double px = hasCatFrame ? mx : x;
            double py = hasCatFrame ? my : y;
            double pz = hasCatFrame ? mz : z;

            if (hasCatFrame)
                AppendCatalogFrameUndo(sb, varName, catFrame!, indent);

            bool placed = false;
            foreach (RotationJog jog in node.RotationJogs!)
            {
                char axis = char.ToUpperInvariant(jog.Axis);
                double deg = jog.Degrees;
                if (jog.World)
                {
                    if (placed)
                    {
                        AppendMove(sb, varName, -px, -py, -pz, indent);
                        placed = false;
                    }

                    AppendConjugatedJogRotate(sb, varName, catFrame, axis, deg, indent);
                }
                else
                {
                    if (!placed && hasMove)
                    {
                        AppendMove(sb, varName, px, py, pz, indent);
                        placed = true;
                    }

                    if (hasMove)
                        AppendMove(sb, varName, -px, -py, -pz, indent);

                    AppendConjugatedJogRotate(sb, varName, catFrame, axis, deg, indent);

                    if (hasMove)
                        AppendMove(sb, varName, px, py, pz, indent);
                }
            }

            if (hasMove && !placed)
                AppendMove(sb, varName, px, py, pz, indent);

            if (hasCatFrame)
                AppendCatalogFrameRedo(sb, varName, catFrame!, indent);
        }

        private static void AppendCatalogFrameUndo(StringBuilder sb, string varName, double[] catFrame, string indent) =>
            AppendMatrixRotation(sb, varName, TransformMath.InvertRotation(catFrame), indent);

        private static void AppendCatalogFrameRedo(StringBuilder sb, string varName, double[] catFrame, string indent) =>
            AppendMatrixRotation(sb, varName, catFrame, indent);

        private static void AppendMatrixRotation(
            StringBuilder sb, string varName, double[] matrix, string indent) =>
            sb.AppendLine(
                $"{indent}{varName} = {varName}.apply_matrix_rotation([{FmtMatrix(matrix)}])");

        private static void AppendMove(
            StringBuilder sb, string varName, double x, double y, double z, string indent) =>
            sb.AppendLine($"{indent}{varName} = {varName}.move(x={Fmt(x)}, y={Fmt(y)}, z={Fmt(z)})");

        private static void AppendConjugatedJogRotate(
            StringBuilder sb,
            string varName,
            double[]? catalogFrame,
            char axis,
            double deg,
            string indent)
        {
            if (catalogFrame == null || catalogFrame.Length < 9 || TransformMath.IsIdentityRotation(catalogFrame))
            {
                sb.AppendLine($"{indent}{varName} = {varName}.rotate{axis}({Fmt(deg)})");
                return;
            }

            double[] body = TransformMath.ConjugateRotationToBuildFrame(catalogFrame, axis, deg);
            sb.AppendLine($"{indent}{varName} = {varName}.apply_matrix_rotation([{FmtMatrix(body)}])");
        }

        private static string FmtMatrix(double[] m) =>
            string.Join(", ", Array.ConvertAll(m, Fmt));

        private static bool TryEulerDegrees(double[] rot, out double xDeg, out double yDeg, out double zDeg)
        {
            xDeg = yDeg = zDeg = 0;
            if (rot == null || rot.Length < 9)
                return false;

            double r00 = rot[0], r01 = rot[1], r02 = rot[2];
            double r10 = rot[3], r11 = rot[4], r12 = rot[5];
            double r20 = rot[6], r21 = rot[7], r22 = rot[8];

            double sy = Math.Sqrt(r00 * r00 + r10 * r10);
            if (sy > 1e-8)
            {
                xDeg = Math.Atan2(r21, r22) * 180.0 / Math.PI;
                yDeg = Math.Atan2(-r20, sy) * 180.0 / Math.PI;
                zDeg = Math.Atan2(r10, r00) * 180.0 / Math.PI;
            }
            else
            {
                xDeg = Math.Atan2(-r12, r11) * 180.0 / Math.PI;
                yDeg = Math.Atan2(-r20, sy) * 180.0 / Math.PI;
                zDeg = 0;
            }

            return Math.Abs(xDeg) > 1e-6 || Math.Abs(yDeg) > 1e-6 || Math.Abs(zDeg) > 1e-6;
        }

        private static string VarName(PrimitiveNode node)
        {
            var chars = node.Name.ToLowerInvariant()
                .Select(c => char.IsLetterOrDigit(c) ? c : '_')
                .ToArray();
            string n = new string(chars).Trim('_');
            if (string.IsNullOrEmpty(n))
                n = "part";
            if (char.IsDigit(n[0]))
                n = "p_" + n;
            return n;
        }

        private static double Param(PrimitiveNode node, string key, double fallback = 0) =>
            node.Parameters.TryGetValue(key, out ParamValue? pv) ? pv.Value : fallback;

        private static string Fmt(double v) =>
            v.ToString("0.######", CultureInfo.InvariantCulture);

        private static string FmtInt(double v) =>
            ((int)Math.Round(v)).ToString(CultureInfo.InvariantCulture);

        private static string EscapePy(string s) =>
            s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
