"""ELBOW 45 SW CL3000 ASTM A105N ASME B16.11

NATIVE reconstruction of Plant 3D CPB_OFOF. Dimensions from CATA_NUI.xlsx
sheet "ELBOW 45_3000_SW". Auto-generated by scripts/gen_native_parts.py — do not edit by hand.
"""

import native_shapes
import pipe_sizes

# DN -> (D, R, A, L1, I1, L2, I2, wall, socket_bore, body_od)
DIMENSIONS = {
    15: (28.91, 12.03, 45.0, 20.5, 9.5, 0.0, 0.0, 3.73, 22.0, 21.34),
    20: (34.28, 14.76, 45.0, 25.0, 12.5, 0.0, 0.0, 3.91, 27.4, 26.67),
    25: (41.87, 18.25, 45.0, 26.5, 12.5, 0.0, 0.0, 4.55, 34.1, 33.4),
    32: (50.64, 22.75, 45.0, 30.0, 12.5, 0.0, 0.0, 4.85, 42.9, 42.16),
    40: (56.74, 25.88, 45.0, 33.0, 12.5, 0.0, 0.0, 5.08, 49.0, 48.26),
    50: (69.26, 32.19, 45.0, 41.5, 16.0, 0.0, 0.0, 3.91, 61.45, 60.32),
}


class ELBOW_45_3000_SW(native_shapes.NativeElbowSocket):
    def __init__(self, s, size, *, add_ports=True):
        key = pipe_sizes.resolve_dn(size)
        if key not in DIMENSIONS:
            raise ValueError(f"No ELBOW_45_3000_SW data for {key}.")
        D, R, A, L1, I1, L2, I2, wall, socket_bore, body_od = DIMENSIONS[key]
        super().__init__(s, D, R, A, L1, I1, L2, I2, wall, socket_bore, body_od, add_ports=add_ports)
