"""ELBOW 45 BV SCH40 ASTM A234-WPB ASME B16.9

NATIVE reconstruction of Plant 3D CPB. Dimensions from CATA_NUI.xlsx
sheet "ELBOW 45_SCH40_BW". Auto-generated by scripts/gen_native_parts.py — do not edit by hand.
"""

import native_shapes
import pipe_sizes

# DN -> (D, R, A, wall)
DIMENSIONS = {
    50: (60.325, 76.2, 45.0, 3.91),
    65: (73.025, 95.25, 45.0, 4.78),
    80: (88.9, 114.3, 45.0, 5.49),
    90: (102.3937, 133.35, 45.0, 5.74),
    100: (114.3, 151.6062, 45.0, 6.02),
    125: (141.2875, 189.7063, 45.0, 6.55),
    150: (168.275, 229.3938, 45.0, 7.11),
    200: (219.075, 304.8, 45.0, 8.18),
    250: (273.05, 381.0, 45.0, 9.27),
    300: (323.85, 457.2, 45.0, 10.31),
    350: (356.3938, 532.6063, 45.0, 11.13),
    400: (405.6062, 610.3937, 45.0, 12.7),
    450: (457.2, 685.8, 45.0, 14.27),
}


class ELBOW_45_SCH40_BW(native_shapes.NativeElbow):
    def __init__(self, s, size, *, add_ports=True):
        key = pipe_sizes.resolve_dn(size)
        if key not in DIMENSIONS:
            raise ValueError(f"No ELBOW_45_SCH40_BW data for {key}.")
        D, R, A, wall = DIMENSIONS[key]
        super().__init__(s, D, R, A, wall, add_ports=add_ports)
