"""ELBOW 90 BV SCH40 ASTM A234-WPB ASME B16.9

NATIVE reconstruction of Plant 3D CPB. Dimensions from CATA_NUI.xlsx
sheet "ELBOW 90_SCH40_BW". Auto-generated by scripts/gen_native_parts.py — do not edit by hand.
"""

import native_shapes
import pipe_sizes

# DN -> (D, R, A, wall)
DIMENSIONS = {
    50: (60.32, 76.0, 90.0, 3.91),
    65: (73.03, 95.0, 90.0, 4.78),
    80: (88.9, 114.0, 90.0, 5.49),
    90: (90.0, 133.0, 90.0, 5.74),
    100: (114.3, 152.0, 90.0, 6.02),
    125: (125.0, 190.0, 90.0, 6.55),
    150: (168.3, 229.0, 90.0, 7.11),
    200: (219.1, 305.0, 90.0, 8.18),
    250: (273.1, 381.0, 90.0, 9.27),
    300: (323.9, 457.0, 90.0, 10.31),
    350: (355.6, 533.0, 90.0, 11.13),
    400: (406.4, 610.0, 90.0, 12.7),
    450: (457.2, 686.0, 90.0, 14.27),
}


class ELBOW_90_SCH40_BW(native_shapes.NativeElbow):
    def __init__(self, s, size, *, add_ports=True):
        key = pipe_sizes.resolve_dn(size)
        if key not in DIMENSIONS:
            raise ValueError(f"No ELBOW_90_SCH40_BW data for {key}.")
        D, R, A, wall = DIMENSIONS[key]
        super().__init__(s, D, R, A, wall, add_ports=add_ports)
