"""PIPE BV SCH40 CS ASTM A53-B ASME B36.10

NATIVE reconstruction of Plant 3D CPP. Dimensions from CATA_NUI.xlsx
sheet "PIPE_SCH40_BV". Auto-generated by scripts/gen_native_parts.py — do not edit by hand.
"""

import native_shapes
import pipe_sizes

# DN -> (D, L, DI)
DIMENSIONS = {
    50: (60.32, 180.96, 52.5),
    65: (73.03, 219.09, 63.47),
    80: (88.9, 266.7, 77.92),
    90: (90.0, 270.0, 78.52),
    100: (114.3, 342.9, 102.26),
    125: (125.0, 375.0, 111.9),
    150: (168.3, 504.9, 154.08),
    200: (219.1, 657.3, 202.74),
    250: (273.1, 819.3, 254.56),
    300: (323.9, 971.7, 303.28),
    350: (355.6, 1066.8, 333.34),
    400: (406.4, 1219.2, 381.0),
    450: (457.2, 1371.6, 428.66),
}


class PIPE_SCH40_BV(native_shapes.NativePipe):
    def __init__(self, s, size, *, add_ports=True):
        key = pipe_sizes.resolve_dn(size)
        if key not in DIMENSIONS:
            raise ValueError(f"No PIPE_SCH40_BV data for {key}.")
        D, L, DI = DIMENSIONS[key]
        super().__init__(s, D, L, DI, add_ports=add_ports)
