"""FLANGE LJ_RF_CL150

NATIVE reconstruction of Plant 3D CPFLR. Dimensions from CATA_NUI.xlsx
sheet "FLANGE LJ_RF_CL150". Auto-generated by scripts/gen_native_parts.py — do not edit by hand.
"""

import native_shapes
import pipe_sizes

# DN -> (L, D1, D2)
DIMENSIONS = {
    15: (11.2, 90.0, 22.9),
    20: (12.7, 100.0, 28.2),
    25: (14.3, 110.0, 34.9),
    32: (15.9, 115.0, 43.7),
    40: (17.5, 125.0, 50.0),
    50: (19.1, 150.0, 62.5),
    65: (22.3, 180.0, 75.4),
    80: (23.9, 190.0, 91.4),
    90: (23.9, 215.0, 104.1),
    100: (23.9, 230.0, 116.8),
    125: (23.9, 255.0, 144.4),
    150: (25.4, 280.0, 171.4),
    200: (28.6, 345.0, 222.2),
    250: (30.2, 405.0, 277.4),
    300: (31.8, 485.0, 328.2),
    350: (35.0, 535.0, 360.2),
    400: (36.6, 595.0, 411.2),
    450: (39.7, 635.0, 462.3),
}


class FLANGE_LJ_RF_CL150(native_shapes.NativeLapJointFlange):
    def __init__(self, s, size, *, add_ports=True):
        key = pipe_sizes.resolve_dn(size)
        if key not in DIMENSIONS:
            raise ValueError(f"No FLANGE_LJ_RF_CL150 data for {key}.")
        L, D1, D2 = DIMENSIONS[key]
        super().__init__(s, L, D1, D2, add_ports=add_ports)
