"""FLANGE SW FL RF CL150 CS ASTM A105N ASME B16.5

NATIVE reconstruction of Plant 3D CPFWR_F_SF. Dimensions from CATA_NUI.xlsx
sheet "FLANGE SW_CL150_RF". Auto-generated by scripts/gen_native_parts.py — do not edit by hand.
"""

import native_shapes
import pipe_sizes

# DN -> (L, B, D1, D2, D3, I)
DIMENSIONS = {
    15: (15.5, 11.2, 89.0, 21.34, 30.0, 10.0),
    20: (15.5, 12.7, 99.0, 26.67, 38.0, 11.0),
    25: (17.5, 14.2, 108.0, 33.4, 49.0, 13.0),
    32: (20.5, 15.7, 117.0, 42.16, 59.0, 14.0),
    40: (22.5, 17.4, 127.0, 48.26, 65.0, 16.0),
    50: (25.5, 19.0, 152.0, 60.32, 78.0, 17.0),
}


class FLANGE_SW_CL150_RF(native_shapes.NativeSlipOnFlange):
    def __init__(self, s, size, *, add_ports=True):
        key = pipe_sizes.resolve_dn(size)
        if key not in DIMENSIONS:
            raise ValueError(f"No FLANGE_SW_CL150_RF data for {key}.")
        L, B, D1, D2, D3, I = DIMENSIONS[key]
        super().__init__(s, L, B, D1, D2, D3, socket_depth=I, add_ports=add_ports)
