"""TEE RED SW CL3000 ASTM A105N ASME B16.11

NATIVE reconstruction of Plant 3D CPTS_OFOFOF. Dimensions from CATA_NUI.xlsx
sheet "TEE RED_3000_SW". Auto-generated by scripts/gen_native_parts.py — do not edit by hand.
"""

import native_shapes
import pipe_sizes

# DN -> (D1, D3, L1, L2, L3, I1, I2, I3, A, wall, socket_bore, body_od, body_od3)
DIMENSIONS = {
    20: (34.28, 0.0, 19.0, 0.0, 0.0, 12.5, 0.0, 9.5, 90.0, 3.91, 27.4, 26.67, 21.3),
    25: (41.87, 0.0, 22.5, 0.0, 0.0, 12.5, 0.0, 9.5, 90.0, 4.55, 34.1, 33.4, 21.3),
    32: (50.64, 0.0, 27.0, 0.0, 0.0, 12.5, 0.0, 9.5, 90.0, 4.85, 42.9, 42.16, 21.3),
    40: (56.74, 0.0, 32.0, 0.0, 0.0, 12.5, 0.0, 9.5, 90.0, 5.08, 49.0, 48.26, 21.3),
    50: (69.26, 0.0, 38.0, 0.0, 0.0, 16.0, 0.0, 9.5, 90.0, 3.91, 61.45, 60.32, 21.3),
}


class TEE_RED_3000_SW(native_shapes.NativeTeeSocket):
    def __init__(self, s, size, *, add_ports=True):
        key = pipe_sizes.resolve_dn(size)
        if key not in DIMENSIONS:
            raise ValueError(f"No TEE_RED_3000_SW data for {key}.")
        D1, D3, L1, L2, L3, I1, I2, I3, A, wall, socket_bore, body_od, body_od3 = DIMENSIONS[key]
        super().__init__(s, D1, D3, L1, L2, L3, I1, I2, I3, A, wall, socket_bore, body_od, body_od3, add_ports=add_ports)
