"""BLIND FLANGE FL RF CL150 CS ASTM A105N ASME B16.5

NATIVE reconstruction of Plant 3D CPFBR. Dimensions from CATA_NUI.xlsx
sheet "BLIND FLANGE_CL150_RF". Auto-generated by scripts/gen_native_parts.py — do not edit by hand.
"""

import native_shapes
import pipe_sizes

# DN -> (L, D)
DIMENSIONS = {
    15: (11.2, 89.0),
    20: (12.7, 99.0),
    25: (14.2, 108.0),
    32: (15.7, 117.0),
    40: (17.4, 127.0),
    50: (19.0, 152.0),
    65: (22.1, 178.0),
    80: (23.9, 190.0),
    90: (23.9, 216.0),
    100: (23.9, 229.0),
    125: (23.9, 254.0),
    150: (25.4, 279.0),
    200: (28.4, 343.0),
    250: (29.9, 406.0),
    300: (31.7, 483.0),
    350: (34.8, 533.0),
    400: (36.6, 597.0),
    450: (39.6, 635.0),
}


class BLIND_FLANGE_CL150_RF(native_shapes.NativeBlindFlange):
    def __init__(self, s, size, *, add_ports=True):
        key = pipe_sizes.resolve_dn(size)
        if key not in DIMENSIONS:
            raise ValueError(f"No BLIND_FLANGE_CL150_RF data for {key}.")
        L, D = DIMENSIONS[key]
        super().__init__(s, L, D, add_ports=add_ports)
