"""FLANGE WN FL RF CL150 CS ASTM A105N ASME B16.5

NATIVE reconstruction of Plant 3D CPFWR. Dimensions from CATA_NUI.xlsx
sheet "FLANGE WN_CL150_RF". Auto-generated by scripts/gen_native_parts.py — do not edit by hand.
"""

import native_shapes
import pipe_sizes

# DN -> (L, B, D1, D2, D3, I)
DIMENSIONS = {
    15: (47.5, 11.2, 89.0, 21.3, 30.0, 0.0),
    20: (52.5, 12.7, 99.0, 26.7, 38.0, 0.0),
    25: (55.5, 14.2, 108.0, 33.4, 49.0, 0.0),
    32: (57.5, 15.7, 117.0, 42.2, 59.0, 0.0),
    40: (61.5, 17.4, 127.0, 48.3, 65.0, 0.0),
    50: (63.5, 19.0, 152.0, 60.3, 78.0, 0.0),
    65: (69.5, 22.1, 178.0, 73.0, 90.0, 0.0),
    80: (69.5, 23.9, 190.0, 88.9, 108.0, 0.0),
    90: (71.5, 23.9, 216.0, 101.6, 122.0, 0.0),
    100: (76.5, 23.9, 229.0, 114.3, 135.0, 0.0),
    125: (88.5, 23.9, 254.0, 141.3, 164.0, 0.0),
    150: (88.5, 25.4, 279.0, 168.3, 192.0, 0.0),
    200: (101.5, 28.4, 343.0, 219.1, 246.0, 0.0),
    250: (101.5, 29.9, 406.0, 273.0, 305.0, 0.0),
    300: (114.5, 31.7, 483.0, 323.8, 365.0, 0.0),
    350: (126.5, 34.8, 533.0, 355.6, 400.0, 0.0),
    400: (126.5, 36.6, 597.0, 406.4, 457.0, 0.0),
    450: (139.5, 39.6, 635.0, 457.2, 505.0, 0.0),
}


class FLANGE_WN_CL150_RF(native_shapes.NativeWeldNeckFlange):
    def __init__(self, s, size, *, add_ports=True):
        key = pipe_sizes.resolve_dn(size)
        if key not in DIMENSIONS:
            raise ValueError(f"No FLANGE_WN_CL150_RF data for {key}.")
        L, B, D1, D2, D3, I = DIMENSIONS[key]
        super().__init__(s, L, B, D1, D2, D3, socket_depth=I, add_ports=add_ports)
