"""TEE RED BV SCH40 ASTM A234-WPB ASME B16.9

NATIVE reconstruction of Plant 3D CPTS. Dimensions from CATA_NUI.xlsx
sheet "TEE RED_SCH40_BW". Auto-generated by scripts/gen_native_parts.py — do not edit by hand.
"""

import native_shapes
import pipe_sizes

# DN -> (D1, D3, L1, L2, L3, A, wall)
DIMENSIONS = {
    20: (26.67, 21.34, 29.0, 0.0, 29.0, 90.0, 3.91),
    25: (33.4, 26.67, 38.0, 0.0, 38.0, 90.0, 4.55),
    32: (42.16, 33.4, 48.0, 0.0, 48.0, 90.0, 4.85),
    40: (48.26, 42.16, 57.0, 0.0, 57.0, 90.0, 5.08),
    50: (60.32, 48.26, 64.0, 0.0, 60.0, 90.0, 3.91),
    65: (73.03, 60.32, 76.0, 0.0, 70.0, 90.0, 4.78),
    80: (88.9, 73.03, 86.0, 0.0, 83.0, 90.0, 5.49),
    90: (90.0, 88.9, 95.0, 0.0, 92.0, 90.0, 5.74),
    100: (114.3, 90.0, 105.0, 0.0, 102.0, 90.0, 6.02),
    125: (125.0, 114.3, 124.0, 0.0, 117.0, 90.0, 6.55),
    150: (168.3, 125.0, 143.0, 0.0, 137.0, 90.0, 7.11),
    200: (219.1, 168.3, 178.0, 0.0, 168.0, 90.0, 8.18),
    250: (273.1, 219.1, 216.0, 0.0, 203.0, 90.0, 9.27),
    400: (406.4, 355.6, 305.0, 0.0, 305.0, 90.0, 12.7),
}


class TEE_RED_SCH40_BW(native_shapes.NativeTee):
    def __init__(self, s, size, *, add_ports=True):
        key = pipe_sizes.resolve_dn(size)
        if key not in DIMENSIONS:
            raise ValueError(f"No TEE_RED_SCH40_BW data for {key}.")
        D1, D3, L1, L2, L3, A, wall = DIMENSIONS[key]
        super().__init__(s, D1, D3, L1, L2, L3, A, wall, add_ports=add_ports)
