"""Generate CatalogStubEndTable.cs + CatalogLjRingCl150Table.cs from pipe_sizes.py (single source)."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "catalog_generator"))

import pipe_sizes  # noqa: E402

CS_DIR = ROOT / "Plant3DCatalogComposer" / "Services"
HEADER = "// <auto-generated by scripts/sync_lap_joint_cs_tables.py — do not edit by hand>\n"


def fmt_row(items: list) -> str:
    inner = ", ".join(str(x) if not isinstance(x, float) else f"{x:g}" for x in items)
    return f"({inner})"


def write_stub_end_table() -> None:
    lines = [
        HEADER,
        "using System;",
        "using System.Collections.Generic;",
        "using System.Linq;",
        "",
        "namespace Plant3DCatalogComposer.Services",
        "{",
        "    /// <summary>ASME B16.9 Type A lap-joint stub end — STUBEND TABLE (mm).</summary>",
        "    internal static class CatalogStubEndTable",
        "    {",
        "        internal enum Pattern { Long, Short }",
        "",
        "        /// <summary>L=total length, B=lap thickness, D1=lap OD, D2=do at weld.</summary>",
        "        internal sealed record StubEndDims(double L, double B, double D1, double D2);",
        "",
        "        private static readonly Dictionary<int, (double Do, double FSh, double FLg, double G, double StubThk)> ByDn = new()",
        "        {",
    ]
    for dn in sorted(pipe_sizes.STUBEND_LJ_A_MM):
        r = pipe_sizes.STUBEND_LJ_A_MM[dn]
        lines.append(
            f"            [{dn}] = {fmt_row([r['do'], r['F_sh'], r['F_lg'], r['G'], r['stub_thk']])},"
        )
    lines += [
        "        };",
        "",
        "        public static IReadOnlyList<int> AllDns { get; } = ByDn.Keys.OrderBy(k => k).ToList();",
        "",
        "        public static Pattern ResolvePattern(string partId) =>",
        "            partId.Contains(\"_SH_\", StringComparison.OrdinalIgnoreCase)",
        "                ? Pattern.Short",
        "                : Pattern.Long;",
        "",
        "        public static bool TryGet(int dn, Pattern pattern, out StubEndDims dims)",
        "        {",
        "            if (!ByDn.TryGetValue(dn, out (double Do, double FSh, double FLg, double G, double StubThk) row))",
        "            {",
        "                dims = default!;",
        "                return false;",
        "            }",
        "",
        "            double l = pattern == Pattern.Short ? row.FSh : row.FLg;",
        "            dims = new StubEndDims(l, row.StubThk, row.G, row.Do);",
        "            return true;",
        "        }",
        "",
        "        public static bool TryGet(int dn, out StubEndDims dims) => TryGet(dn, Pattern.Long, out dims);",
        "",
        "        /// <summary>Lap thickness B (mm) — same for long/short pattern.</summary>",
        "        public static bool TryGetLapThickness(int dn, out double lapMm)",
        "        {",
        "            if (!ByDn.TryGetValue(dn, out (double Do, double FSh, double FLg, double G, double StubThk) row))",
        "            {",
        "                lapMm = 0;",
        "                return false;",
        "            }",
        "            lapMm = row.StubThk;",
        "            return true;",
        "        }",
        "",
        "        /// <summary>Stub OD at pipe weld (do / catalog D2) — MatchingPipeOd for all lap-joint ports.</summary>",
        "        public static bool TryGetWeldDo(int dn, out double doMm)",
        "        {",
        "            if (!ByDn.TryGetValue(dn, out (double Do, double FSh, double FLg, double G, double StubThk) row))",
        "            {",
        "                doMm = 0;",
        "                return false;",
        "            }",
        "            doMm = row.Do;",
        "            return true;",
        "        }",
        "",
        "        public static StubEndDims Get(int dn, Pattern pattern) =>",
        "            TryGet(dn, pattern, out StubEndDims dims)",
        "                ? dims",
        "                : throw new InvalidOperationException($\"No stub end table row for DN {dn}.\");",
        "    }",
        "}",
        "",
    ]
    (CS_DIR / "CatalogStubEndTable.cs").write_text("\n".join(lines), encoding="utf-8")


def write_lj_ring_table() -> None:
    lines = [
        HEADER,
        "using System;",
        "using System.Collections.Generic;",
        "using System.Linq;",
        "",
        "namespace Plant3DCatalogComposer.Services",
        "{",
        "    /// <summary>CL150 lap-joint flat plate — ASME B16.5 Table 7 O/W + Table 8 tf (mm).</summary>",
        "    internal static class CatalogLjRingCl150Table",
        "    {",
        "        internal sealed record LjRingDims(double L, double D1, double D2, double Tf);",
        "",
        "        private static readonly Dictionary<int, (double L, double D1, double D2, double Tf)> ByDn = new()",
        "        {",
    ]
    for dn in sorted(pipe_sizes.LJ_RING_CL150_DNS):
        d = pipe_sizes.lj_ring_cl150_dims_mm(dn)
        lines.append(
            f"            [{dn}] = {fmt_row([d['L'], d['O'], d['D2'], d['tf']])},"
        )
    lines += [
        "        };",
        "",
        "        public static IReadOnlyList<int> AllDns { get; } = ByDn.Keys.OrderBy(k => k).ToList();",
        "",
        "        public static bool TryGet(int dn, out LjRingDims dims)",
        "        {",
        "            if (!ByDn.TryGetValue(dn, out (double L, double D1, double D2, double Tf) row))",
        "            {",
        "                dims = default!;",
        "                return false;",
        "            }",
        "            dims = new LjRingDims(row.L, row.D1, row.D2, row.Tf);",
        "            return true;",
        "        }",
        "",
        "        public static LjRingDims Get(int dn) =>",
        "            TryGet(dn, out LjRingDims dims)",
        "                ? dims",
        "                : throw new InvalidOperationException($\"No CL150 LJ ring for DN {dn}.\");",
        "    }",
        "}",
        "",
    ]
    (CS_DIR / "CatalogLjRingCl150Table.cs").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    write_stub_end_table()
    write_lj_ring_table()
    print(f"Wrote {CS_DIR / 'CatalogStubEndTable.cs'}")
    print(f"Wrote {CS_DIR / 'CatalogLjRingCl150Table.cs'}")
    print(f"  stub DN: {len(pipe_sizes.STUBEND_LJ_A_MM)}")
    print(f"  ring DN: {len(pipe_sizes.LJ_RING_CL150_DNS)}")


if __name__ == "__main__":
    main()
