"""PIPE PL SCH80 CS ASTM A106-B ASME B36.10

NATIVE reconstruction of Plant 3D CPP. Dimensions from CATA_NUI.xlsx
sheet "PIPE_SCH80_PL". Auto-generated by scripts/gen_native_parts.py — do not edit by hand.
"""

import native_shapes
import pipe_sizes

# DN -> (D, L, DI)
DIMENSIONS = {
    15: (21.34, 64.02, 13.88),
    20: (26.67, 80.01, 18.85),
    25: (33.4, 100.2, 24.3),
    32: (42.16, 126.48, 32.46),
    40: (48.26, 144.78, 38.1),
    50: (60.32, 180.96, 52.5),
}


class PIPE_SCH80_PL(native_shapes.NativePipe):
    def __init__(self, s, size, *, add_ports=True):
        key = pipe_sizes.resolve_dn(size)
        if key not in DIMENSIONS:
            raise ValueError(f"No PIPE_SCH80_PL data for {key}.")
        D, L, DI = DIMENSIONS[key]
        super().__init__(s, D, L, DI, add_ports=add_ports)
